import os

AI_ANALYSIS_SAVED_AS_MARKDOWN: bool = os.getenv('AI_ANALYSIS_SAVED_AS_MARKDOWN', 'False').lower() in ('true', '1', 't')

# save scraped data as JSON
OUTPUT_FILENAME_API_DETAILS: str = os.getenv('OUTPUT_FILENAME_API_DETAILS')
DATA_SCRAPING_SAVE_API_DETAILS: bool = len(os.getenv('OUTPUT_FILENAME_API_DETAILS')) > 0

# save cleaned data as JSON
OUTPUT_FILENAME_SONGS_DETAILS: str = os.getenv('OUTPUT_FILENAME_SONGS_DETAILS')
DATA_SCRAPING_SAVE_SONGS_DETAILS: bool = len(os.getenv('OUTPUT_FILENAME_SONGS_DETAILS')) > 0
SPOTIFY_PLAYLIST_UI_END_SCROLL_ELEMENT: str = os.getenv('SPOTIFY_PLAYLIST_UI_END_SCROLL_ELEMENT', 'RD3ze5s5sQ4S4Tyb')
