import os

IS_ENVIRONMENT_CLOUD: bool = os.getenv('ENVIRONMENT_CLOUD', 'False').lower() in ('true', '1', 't')

# save scraped data as JSON
OUTPUT_FILENAME_API_DETAILS: str = os.getenv('OUTPUT_FILENAME_API_DETAILS', '')
IS_SAVE_API_DETAILS: bool = len(OUTPUT_FILENAME_API_DETAILS) > 0

# save cleaned data as JSON
OUTPUT_FILENAME_SONGS_DETAILS: str = os.getenv('OUTPUT_FILENAME_SONGS_DETAILS', '')
IS_SAVE_SONG_DETAILS: bool = len(OUTPUT_FILENAME_SONGS_DETAILS) > 0
SPOTIFY_PLAYLIST_UI_END_SCROLL_ELEMENT: str = os.getenv('SPOTIFY_PLAYLIST_UI_END_SCROLL_ELEMENT', 'RD3ze5s5sQ4S4Tyb')
